"use strict";
const {
    permissionIds,
    roleIds,
    moduleIds,
    designationIds,
} = require("../../server/configs/Constants");
const itInternee = "852cdf35-5dd3-5a3f-8134-d8a773b3eb70"
const embeddedInternee = "852cdf35-5dd3-5a4f-8134-d8a773b3eb70"
module.exports = {
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert("permissions", [
            {
                id: permissionIds[115],
                moduleId: moduleIds[7],
                read: true,
                update: true,
                write: true,
                delete: true,
                self: false,
                roleId: roleIds[0],
                designationId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[116],
                moduleId: moduleIds[7],
                read: true,
                update: false,
                write: true,
                delete: true,
                self: false,
                roleId: roleIds[2],
                designationId: null,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[117],
                moduleId: moduleIds[7],
                read: true,
                update: true,
                write: true,
                delete: true,
                self: false,
                roleId: roleIds[1],
                designationId: designationIds.ceo,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[118],
                moduleId: moduleIds[7],
                read: true,
                update: false,
                write: false,
                delete: false,
                self: false,
                roleId: roleIds[1],
                designationId: itInternee,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[119],
                moduleId: moduleIds[7],
                read: true,
                update: false,
                write: false,
                delete: false,
                self: false,
                roleId: roleIds[1],
                designationId: embeddedInternee,
                createdAt: new Date(),
                updatedAt: new Date(),
            }, {
                id: permissionIds[120],
                moduleId: moduleIds[7],
                read: true,
                update: false,
                write: false,
                delete: false,
                self: false,
                roleId: roleIds[1],
                designationId: designationIds.embeddedEngineer,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[121],
                moduleId: moduleIds[7],
                read: true,
                update: false,
                write: false,
                delete: false,
                self: false,
                roleId: roleIds[1],
                designationId: designationIds.softwareEngineer,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[122],
                moduleId: moduleIds[7],
                read: true,
                update: true,
                write: true,
                delete: true,
                self: false,
                roleId: roleIds[1],
                designationId: designationIds.teamLead,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[123],
                moduleId: moduleIds[6],
                read: false,
                update: false,
                write: false,
                delete: false,
                self: false,
                roleId: roleIds[1],
                designationId: itInternee,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
            {
                id: permissionIds[124],
                moduleId: moduleIds[6],
                read: false,
                update: false,
                write: false,
                delete: false,
                self: false,
                roleId: roleIds[1],
                designationId: embeddedInternee,
                createdAt: new Date(),
                updatedAt: new Date(),
            },
        ]);
    },

    async down(queryInterface, Sequelize) {
        /**
         * Add commands to revert seed here.
         *
         * Example:
         */
        await queryInterface.bulkDelete("permissions", null, {});
    },
};
