const express = require("express");

const usersRouter = require("./routes/User.route");
const tasksRouter = require("./routes/Task.route");
const projectsRouter = require("./routes/Project.route");
const publicRouter = require("./routes/Public.route");
const conversationRouter = require("./routes/Conversation.route");
const storageRouter = require("./routes/Storage.route");
const notificationRouter = require("./routes/Notification.route");
const projectEmployeeRouter = require("./routes/ProjectEmployee.route");
const experienceRouter = require("./routes/Experience.route");
const salaryRouter = require("./routes/Salary.route");
const incentiveRouter = require("./routes/Incentive.route");
const salaryDetailRouter = require("./routes/SalaryDetail.route");
const departmentRouter = require("./routes/Department.route");
const PaymentHeadRouter = require("./routes/PaymentHead.route");
const PaymentRouter = require("./routes/Payment.route");
const questionRouter = require("./routes/Question.route");
const testRouter = require("./routes/Test.route");
const roleRouter = require("./routes/Role.route");
const moduleRouter = require("./routes/Module.route");
const designationRouter = require("./routes/Designation.route");
const permissionRouter = require("./routes/Permission.route");
const projectEquipmentRouter = require("./routes/ProjectEquipment.route");
const projectDocumentRouter = require("./routes/ProjectDocument.route");
const commentRouter = require("./routes/Comment.route");
const issueRouter = require("./routes/Issue.route");
const attendanceRouter = require("./routes/Attendance.route");
const educationRouter = require("./routes/EducationInformation.route");
const emergencyContactRouter = require("./routes/EmergencyContact.route");
const holidayRouter = require("./routes/Holiday.route");
const expenseRouter = require("./routes/Expense.route");
const quotationRouter = require("./routes/Quotation.route");
const invoiceRouter = require("./routes/Invoice.route");
const employeeSalaryRouter = require("./routes/EmployeeSalary.route");
const clientTask = require("./routes/ClientTask.route");
const dashBoardRouter = require("./routes/DashBoard.route");
const bugRouter = require("./routes/Bug.route");
const ticketRouter = require("./routes/Ticket.route");
const reportRouter = require("./routes/Reports.route");

const router = express.Router();

router.use("/users", usersRouter);
router.use("/tasks", tasksRouter);
router.use("/projects", projectsRouter);
router.use("/public", publicRouter);
router.use("/conversation", conversationRouter);
router.use("/storage", storageRouter);
router.use("/notifications", notificationRouter);
router.use("/project/employees", projectEmployeeRouter);
router.use("/users/experiences", experienceRouter);
router.use("/users/emergency/contact", emergencyContactRouter);
router.use("/users/education", educationRouter);
router.use("/salary", salaryRouter);
router.use("/incentive", incentiveRouter);
router.use("/salaryDetail", salaryDetailRouter);
router.use("/department", departmentRouter);
router.use("/payment", PaymentRouter);
router.use("/payment/heads", PaymentHeadRouter);
router.use("/question", questionRouter);
router.use("/test", testRouter);
router.use("/role", roleRouter);
router.use("/module", moduleRouter);
router.use("/designation", designationRouter);
router.use("/permission", permissionRouter);
router.use("/projects/equipment", projectEquipmentRouter);
router.use("/projects", projectDocumentRouter);
router.use("/comments", commentRouter);
router.use("/issues", issueRouter);
router.use("/attendance", attendanceRouter);
router.use("/holiday", holidayRouter);
router.use("/expense", expenseRouter);
router.use("/quotation", quotationRouter);
router.use("/invoice", invoiceRouter);
router.use("/employee-salary", employeeSalaryRouter);
router.use("/client-taskboard", clientTask);
router.use("/employeeDashBoard", dashBoardRouter);
router.use("/dashBoard", dashBoardRouter);
router.use("/bug", bugRouter);
router.use("/ticket", ticketRouter);
router.use("/reports", reportRouter);

module.exports = router;
